example/urls.py
from django.contrib import admin
from django.urls import path
import employee

from employee.views import EmployeeImage, EmpImageDisplay

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', employee.views.login),
    path('login_submit/', employee.views.login_submit),
    path('logout', employee.views.logout),
    path('landing', employee.views.landing),
    path('works', employee.views.works),
    path('face_reco/', EmployeeImage.as_view(), name='home'),
    path('digital_makeup/',employee.views.digital_makeup),
    path('find_face/',employee.views.find_face),
    path('face_recognition/',employee.views.face_recog),
    path('find_facial_feature/',employee.views.find_facial_feature),
    path('video_detection/',employee.views.video_detection),
    
    path('emp-image/<int:pk>/', EmpImageDisplay.as_view(), name='emp_image_display'),
]


from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=50)
    emp_image = models.FileField(upload_to='images/')

class Client(models.Model):
    id = models.AutoField(primary_key=True, auto_created=True)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=255, default='c4ca4238a0b923820dcc509a6f75849b')

    class Meta:
        db_table = 'employee_client'

templates/emp_image.html
{% extends "main_template.html" %}
{% block hero %}
<div class="container position-relative text-center text-lg-center mt-5" data-aos="zoom-in" data-aos-delay="100">
    <div class="row">
      <p class="h3 text-center m-auto uppercase">
        {% if data %}
          {{ data }}
        {% else %}
          FACE RECOGNITION
        {% endif %}
    </div>
</div>
{% endblock %}
{% block pagecss %}
<link rel="stylesheet" href="/assets/css/uploadcontainer.css">
<link rel="stylesheet" href="/assets/css/button.css">
{% endblock %}
{% block main_box_wrapper %}
<div class="container mt-5">
    <div class="row">
      <div class="row m-auto">
        <div class="col-12 text-left"> 
          {% if data %}
          <div class="row d-flex justify-content">
            <div class="col-5">
              <img id="tar_image" src="/{{url}}" alt="Smiley face" class="d-block mx-auto w-100">
            </div>
            <div class="col-2">
              <img src="/assets/img/arrow.png" style="margin-top: 100%;" alt="arrow" class="w-100">
            </div>
            <div class="col-5 row">
              <div id="spinner" class="spinner-border m-auto d-none" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
              </div>
              <img id="res_image" src="/{{url}}" alt="Smiley face" class="d-block mx-auto w-100 d-block">
            </div>
          </div>
          <span></span>
          <div class="row mt-3" style="width: 120%;margin-left: -10%;">
            <button type="button" onclick="digital_makeup()" class="mx-2 col mt-3 btn">Digital Make up</button>
            <button type="button" onclick="find_face()" class="mx-2 col mt-3 btn">Face Detection</button>
            <button type="button" onclick="find_facial_feature()" class="mx-2 col mt-3 btn">Find facial feature</button>
            <button type="button" onclick="face_recognition()" class="ml-2 mr-4 col mt-3 btn">Face Recognition</button>
            <form method = "post" enctype="multipart/form-data"> 
              {% csrf_token %} 
              {{ form.as_p }} 
              <button type="submit" class="mx-2 btn col mt-3">Media Upload</button> 
            </form> 
          </div>      
          {% elif video_url %}
          <video style="width: 100%;" controls class="mt-5">
            <source src="/{{video_url}}" type="video/mp4">
          </video>
          <div class="row col-12">
            <button type="button" onclick="video_detection()" class="col-5 btn mr-3">Face Detection</button>  
            <button onclick="location.href='/face_reco/'" class="col-5 btn">Media Upload</button>
          </div>
          {% else %}
          <div id="container" class="m-6 col-12 mt-5 p-5">
            <form method = "post" enctype="multipart/form-data"> 
              {% csrf_token %} 
              <div class="box-input">
                <svg x="0px" y="0px" viewBox="0 0 64 62" style="enable-background:new 0 0 64 62;" xml:space="preserve">
                <style type="text/css">
                  .st0{fill:none;stroke:#fff;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;}
                </style>
                <g id="spa-launch">
                  <path class="st0" d="M33,27.1h-8c0,0-2-6-2-12c0-8,6-14,6-14s6,6,6,14C35,21.1,33,27.1,33,27.1z"/>
                  <line class="st0" x1="29" y1="17.1" x2="29" y2="27.1"/>
                  <polyline class="st0" points="25,27.1 17,27.1 17,23.1 23.1,17.1 	"/>
                  <polyline class="st0" points="33,27.1 41,27.1 41,23.1 34.9,17.1 	"/>
                  <path class="st0" d="M18,41.2c0.5-5.7,5.2-10.1,11-10.1c5.1,0,9.3,3.4,10.6,8.1"/>
                  <path class="st0" d="M48,41.1c-0.2-3.4-3.1-6-6.5-6c-1.2,0-2.4,0.3-3.3,0.9"/>
                  <path class="st0" d="M42.3,47.1c0,0-1-4-6-4"/>
                  <path class="st0" d="M26.3,43.1c-3-1-4,2-4,2s-3-2-5,0s-1,4-1,4"/>
                  <path class="st0" d="M9,46.1c-0.8-0.6-1.9-1-3-1c-2.8,0-5,2.2-5,5s2.2,5,5,5h46c2.8,0,5-2.2,5-5c0-5-4-9-9-9
                    c-0.9,0-1.8,0.1-2.6,0.4"/>
                  <path class="st0" d="M18.8,37.9c-1.1-0.5-2.4-0.8-3.8-0.8c-4.6,0-8.5,3.5-8.9,8"/>
                </g>
                </svg>
                <input type="file" name="emp_image" id="id_emp_image" class="box-file">
                <label for="id_emp_image"><strong>Choose a file</strong><span class="box-dragndrop"> or drag it here</span>.</label>
                <button type="submit" class="button">Upload</button>
              </div>
                    
            </form> 
          </div>
          {% endif %}
        </div>
      </div>
    </div>
</div>
{% endblock %}
{% block pagejs %}
<script>
  function digital_makeup(){
    var tmp  = "{{url}}";
    $.ajax({
        url : "/digital_makeup/", // the endpoint
        type : "GET", // http method
        data : { tar_image : tmp}, // data sent with the get request
        success : function(json) {
          $("#res_image").attr({'src': json});
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        }
    });
  };
  function find_face(){
    var tmp  = "{{url}}";
    $("#spinner").removeClass('d-none');
    $("#spinner").addClass('d-block');
    $("#res_image").addClass('d-none');
    $("#res_image").removeClass('d-block');
    $.ajax({
        url : "/find_face/", // the endpoint
        type : "GET", // http method
        data : { tar_image : tmp}, // data sent with the get request

        // handle a successful response
        success : function(json) {
          $("#res_image").attr({'src': json});
          $("#spinner").addClass('d-none');
          $("#spinner").removeClass('d-block');
          $("#res_image").removeClass('d-none');
          $("#res_image").addClass('d-block');
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        }
    });
  };
  function find_facial_feature(){
    var tmp  = "{{url}}";
    $.ajax({
        url : "/find_facial_feature/", // the endpoint
        type : "GET", // http method
        data : { tar_image : tmp}, // data sent with the get request

        // handle a successful response
        success : function(json) {
          $("#res_image").attr({'src': json});
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        }
    });
  };
  function face_recognition(){
    var tmp  = "{{url}}";
    $("#spinner").removeClass('d-none');
    $("#spinner").addClass('d-block');
    $("#res_image").addClass('d-none');
    $("#res_image").removeClass('d-block');
    $.ajax({
        url : "/face_recognition/", // the endpoint
        type : "GET", // http method
        data : { tar_image : tmp}, // data sent with the get request

        // handle a successful response
        success : function(json) {
          $("#spinner").addClass('d-none');
          $("#spinner").removeClass('d-block');
          $("#res_image").removeClass('d-none');
          $("#res_image").addClass('d-block');
          $("#res_image").attr({'src': json});
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        }
    });
  };
  function video_detection(){
    var tmp  = "{{video_url}}";
    $.ajax({
        url : "/video_detection/", // the endpoint
        type : "GET", // http method
        data : { tar_image : tmp}, // data sent with the get request

        // handle a successful response
        success : function(json) {
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
        }
    });
  };
</script>
{% endblock %}

templates/landing.html
{% extends "main_template.html" %}
{% block hero %}
<div class="container position-relative text-center text-lg-left" data-aos="zoom-in" data-aos-delay="100">
    <div class="row">
    <div class="col-lg-12 effect-bg">
    
        <div class=" lorem">
            <h3>LOREM IPSUM</h3>
        
        <ul>
            
            <li><a href="#about">sample Location</a></li>
            <li><a href="#menu">Main Information</a></li>
            <li><a href="#specials">Communication</a></li>
            
            <li><a href="#gallery">Industries</a></li>
        
            </ul>
        </div>
    </div>
    </div>
</div>
{% endblock %}
{% block main_box_wrapper %}
<div class="container">
    <div class="row">
        <a class="col-lg-4 col-md-6" href="/about">
            <div class="box_wrapper ">
                <div class="icon_box ">
                    <h3><img src="assets/img/effect3.png"></h3>
                    <span> <i class="fa fa-globe" aria-hidden="true"></i> </span>
                    <h4> ABOUT</h4>
                    <p>
                    Technology affects people all over the world. Advances in technology have made our
                        countries safer and our lives easier, they have also negatively affected our lives.
                        Technology have brought us online banking, smart cars, smart TVs, lightning fast computers,
                        and the virtual reality. Also there include cyber warfare, hackers, identity theft, cyber stalking,
                        and a host of other bad things.
                    </p>
                </div>
                <div class="effect-img"><img src="assets/img/effect3.png"></div>
            </div>
        </a>
        
        <a class="col-lg-4 col-md-6" href="/contact">
            <div class="box_wrapper ">
                <div class="icon_box ">
                    <h3><img src="assets/img/effect3.png"></h3>
                    <span> <i class="fa fa-lightbulb-o" aria-hidden="true"></i> </span>
                    <h4> CONTACT</h4>
                    <p>
        Technology affects people all over the world. Advances in technology have made our
                        countries safer and our lives easier, they have also negatively affected our lives.
                        Technology have brought us online banking, smart cars, smart TVs, lightning fast computers,
                        and the virtual reality. Also there include cyber warfare, hackers, identity theft, cyber stalking,
                        and a host of other bad things.
                    </p>
                </div>
                <div class="effect-img"><img src="assets/img/effect3.png"></div>
            </div>
        </a>
        <a class="col-lg-4 col-md-6" href="/face_reco/">
            <div class="box_wrapper ">
                <div class="icon_box ">
                    <h3><img src="assets/img/effect3.png"></h3>
                    <span> <i class="fas fa-camera" aria-hidden="true" style="font-size:70px;" ></i> </span>
                    <h4> FACE RECO</h4>
                    <p>
                    
                        Technology affects people all over the world. Advances in technology have made our
                        countries safer and our lives easier, they have also negatively affected our lives.
                        Technology have brought us online banking, smart cars, smart TVs, lightning fast computers,
                        and the virtual reality. Also there include cyber warfare, hackers, identity theft, cyber stalking,
                        and a host of other bad things.
                    
                    
                    
                    </p>
                </div>
                <div class="effect-img"><img src="assets/img/effect3.png"></div>
            </div>
        </a>
        
    </div>
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
	<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
	<script src="/assets/js/jquery.min.js"></script>
	<script src="/assets/js/bootstrap.min.js"></script>
	<link href="/assets/img/favicon.png" rel="icon">
  <style type="text/css">
	#logincontainer {
		padding: 0px;
		margin: 0px;
	}
	#loginlogo {
		display: block;
		background-image: url(../media/landinglogo.png);
		background-repeat: no-repeat;
		background-size: auto;
		background-position-y: center;
		background-position-x: center;
	}
	@media screen and (max-width: 1500px) {
		#loginlogo {
			background-image: url(../media/landinglogo_small.png);
		}
	}
	#logininputcontainer {
		padding: 0px;
		margin: 0px;
		width: 100%;
		background-image: linear-gradient(140deg, #083169 0%, #19a1d5 50%, #a4e5f9 80%);
	}
	.loginform {
		background-color: #152e4c;
		/* height: 50%; */
		padding-bottom: 50px;
	}
	.btn-custom {
		background-color: #15c5d2;
	}
	.form-control {
		border-radius: 0px;
	}
    #loginlogo p.h1 {
        margin-top: 40%;
        margin-left: 6%;
        font-size: 7rem;
    }
  </style>
</head>
<body>
    <div id="logincontainer" class="container-fluid row">
        <div id="loginlogo" class="col-6 divideContainer mx-auto justify-center">
			<p class="h1">سهم</p>
        </div>
        <div id="logininputcontainer" class="col-6 row divideContainer">
			<div class="justify-center mx-auto my-auto text-white col-8 loginform">
				<p class="h2 text-center mt-5">MEMBER LOGIN</p>
				<form method="POST" action="/login_submit/">
					{% csrf_token %}
					<div class="input-group mt-5 input-group-lg col-10 mx-auto">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="Username" name="username">
					</div>
					<div class="input-group mt-4 input-group-lg col-10 mx-auto">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-password"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="Password" name="password">
					</div>
					<div class="input-group mt-4 input-group-lg col-10 mx-auto">
						<input type="submit" class="form-control btn btn-info btn-custom" value="LOGIN">
					</div>
					<div class="row col-10 mt-3 mx-auto">
						<div class="col">
							<input type="checkbox" id="defaultCheck" name="example2">
    						<label for="defaultCheck">Remember Me</label>
						</div>
						<div class="col">
							<a href="#" class="float-right">Forgot Password?</a>
						</div>
					</div>
				</form>
			</div>
		</div>
    </div>
</body>
<script>
	$(document).ready(function() {
		$(".divideContainer").height(window.innerHeight + "px");
		console.log("{{ obj }}");
	})
</script>
</html>

templates/main_template.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>TECH COM</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/assets/img/favicon.png" rel="icon">
  <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <!-- <link href="/assets/fonts/googleapifonts.css" rel="stylesheet"> -->

  <!-- Vendor CSS Files -->
  <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
  <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="/assets/vendor/owl.carousel//assets/owl.carousel.min.css" rel="stylesheet">
  <link href="/assets/vendor/venobox/venobox.css" rel="stylesheet">
  <link href="/assets/vendor/aos/aos.css" rel="stylesheet">
  <!-- <link rel="stylesheet" type="text/css" href="/assets/css/fonts.css" /> -->
	<!-- <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome.css" /> -->
	<link rel="stylesheet" type="text/css" href="/assets/css/flaticon.css" />
	<!-- <link rel="stylesheet" href="/assets/fonts/font-awesome.min.css"> -->
  <link rel="stylesheet" href="/assets/font-awesome/css/fontawesome.css">

  <!-- Template Main CSS File -->
  <link href="/assets/css/style.css" rel="stylesheet">
  {% block pagecss %}
  {% endblock %}
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex">
      
    </div>
  </div>

  <!-- ======= Header ======= -->
  {% block header %}
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          
          <li><a href="/landing">Main</a></li>
          <li><a href="/landing">Technology</a></li>
          <li><a href="/landing">Support</a></li>
          <li><a href="/landing">Gallery</a></li>
        
          <li><a href="/landing">Contact</a></li>
          
        </ul>
		
		
      </nav><!-- .nav-menu -->
       <div class="search " ><a href="/logout">Log Out</a></div>
    </div>
  </header><!-- End Header -->
  {% endblock %}

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center pt-5">
    {% block hero %}

    {% endblock %}
  </section>
  <!-- End Hero -->
 	<!-- erp pricing list Start -->
	<div class="main_box_wrapper ">
		{% block main_box_wrapper %}

    {% endblock %}
	</div>
	<!-- erp pricing list End -->
  <!-- ======= Footer ======= -->
  <footer id="footer">
    {% block footer %}
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-links">
            <ul>
              <li> <a href="#">Technology has affected society</a></li>
              <li> <a href="#">More abvanced ecpmpmies</a></li>
              <li> <a href="#">Many technologycal processesa</a></li>
              <li> <a href="#">Various implementation</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-links">
            <ul>
              <li> <a href="#">Various implementation</a></li>
              <li> <a href="#">Many technological processes</a></li>
              <li> <a href="#">More advanced ecomies</a></li>
              <li><a href="#">Technology has affecte society</a></li>
              
            </ul>
            </div>
            <div class="col-lg-6 col-md-6">
              <div class="footer-info">

              <div class="social-links mt-3">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="copyright">
         <p> 2021 &copy; All Rights Reserved Name of company</p>
      </div>
    </div>
    {% endblock %}
  </footer>	
   <!-- End footer -->

    <!-- ======= Why Us Section ======= -->
    <!-- End Why Us Section -->

    <!-- ======= Menu Section ======= -->
    <!-- End Menu Section -->

    <!-- ======= Specials Section ======= -->
    <!-- End Specials Section -->

    <!-- ======= Events Section ======= -->
    <!-- End Events Section -->

    <!-- ======= Book A Table Section ======= -->
    <!-- End Book A Table Section -->

    <!-- ======= Testimonials Section ======= -->
   <!-- End Testimonials Section -->

    <!-- ======= Gallery Section ======= -->
    <!-- End Gallery Section -->

    <!-- ======= Chefs Section ======= -->
   

  <div id="preloader"></div>
  <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>

  <!-- Vendor JS Files -->
  <script src="/assets/vendor/jquery/jquery.min.js"></script>
  <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
  <script src="/assets/vendor/php-email-form/validate.js"></script>
  <script src="/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
  <script src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/assets/vendor/venobox/venobox.min.js"></script>
  <script src="/assets/vendor/aos/aos.js"></script>

  <!-- Template Main JS File -->
  <script src="/assets/js/main.js"></script>
  {% block pagejs %}
  {% endblock %}

</body>

</html>

templates/works.html
{% extends "main_template.html" %}
{% block navblock %}
    <li><a href="/landing"><span>Home</span></a></li>
    <li class="is-active"><span><a href="/works">Works</span></a></li>
    <li><span><a href="/aboutus">About</a></span></li>
    <li><span><a href="/contact">Contact</a></span></li>
    <li><span><a href="/hireus">Hire us</a></span></li>
{% endblock %}
{% block contentblock %}
    <li class="l-section section section--is-active">
        <div class="work">
            <h2>Selected work</h2>
            <div class="work--lockup">
            <ul class="slider">
                <li class="slider--item slider--item-left">
                <a href="#0">
                    <div class="slider--item-image">
                    <img src="/static/assets/img/work-victory.jpg" alt="Victory">
                    </div>
                    <p class="slider--item-title">Victory</p>
                    <p class="slider--item-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.</p>
                </a>
                </li>
                <li class="slider--item slider--item-center">
                <a href="#0">
                    <div class="slider--item-image">
                    <img src="/static/assets/img/work-metiew-smith.jpg" alt="Metiew and Smith">
                    </div>
                    <p class="slider--item-title">Metiew &amp; Smith</p>
                    <p class="slider--item-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.</p>
                </a>
                </li>
                <li class="slider--item slider--item-right">
                <a href="#0">
                    <div class="slider--item-image">
                    <img src="/static/assets/img/work-alex-nowak.jpg" alt="Alex Nowak">
                    </div>
                    <p class="slider--item-title">Alex Nowak</p>
                    <p class="slider--item-description">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.</p>
                </a>
                </li>
            </ul>
            <div class="slider--prev">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                viewBox="0 0 150 118" style="enable-background:new 0 0 150 118;" xml:space="preserve">
                <g transform="translate(0.000000,118.000000) scale(0.100000,-0.100000)">
                <path d="M561,1169C525,1155,10,640,3,612c-3-13,1-36,8-52c8-15,134-145,281-289C527,41,562,10,590,10c22,0,41,9,61,29
                c55,55,49,64-163,278L296,510h575c564,0,576,0,597,20c46,43,37,109-18,137c-19,10-159,13-590,13l-565,1l182,180
                c101,99,187,188,193,199c16,30,12,57-12,84C631,1174,595,1183,561,1169z"/>
                </g>
                </svg>
            </div>
            <div class="slider--next">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 150 118" style="enable-background:new 0 0 150 118;" xml:space="preserve">
                <g transform="translate(0.000000,118.000000) scale(0.100000,-0.100000)">
                <path d="M870,1167c-34-17-55-57-46-90c3-15,81-100,194-211l187-185l-565-1c-431,0-571-3-590-13c-55-28-64-94-18-137c21-20,33-20,597-20h575l-192-193C800,103,794,94,849,39c20-20,39-29,61-29c28,0,63,30,298,262c147,144,272,271,279,282c30,51,23,60-219,304C947,1180,926,1196,870,1167z"/>
                </g>
                </svg>
            </div>
            </div>
        </div>
    </li>
{% endblock %}

{% block outernavblock %}
    <li><a href="/landing">Home</a></li>
    <li class="is-active"><a href="/works">Works</a></li>
    <li><a href="/aboutus">About</a></li>
    <li><a href="/contact">Contact</a></li>
    <li><a href="/hireus">Hire us</a></li>
{% endblock %}